name: Deploy pipeline 

on: 
  push: 
    branches:
      - "master"
  pull_request:
    branches: ["master"]
    types: [opened, synchronize]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action
        with: 
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Install dependencies
      #   run: npm install
      # - name: Linter
      #   run: npm run Linter
      # - name: build
      #   run: npm run build
      # - name: Test
      #   run: npm run test
      # - name: deploy
      # if: ${{ github.event_name == 'push'}}
      #   uses: dependencie to hosting deploy
      #   with:
      #   hosting-apk: ${{secrets.hosting_api_key}}